server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: happyvr-backend
  
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:53307/happyvr?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  
  # Flyway配置
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
  
  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
      enabled: true
  
  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

# 应用配置
app:
  # JWT配置
  jwt:
    secret: happyvr-jwt-secret-key-2024-very-long-secure-key-for-hs512-algorithm-minimum-512-bits-required
    expiration: 86400000 # 24小时
  
  # 文件存储配置
  file:
    upload-path: ./uploads/
    base-url: http://localhost:8080/api/files/

# 文件上传配置
file:
  upload:
    base-path: uploads
    base-url: /files
    max-file-size: 10485760 # 10MB
    max-total-size: 104857600 # 100MB
    allowed-types: 
      - image/jpeg
      - image/jpg
      - image/png
    allowed-extensions:
      - .jpg
      - .jpeg
      - .png
  
  # VR处理配置
  vr:
    processing-timeout: 300000 # 5分钟
    max-image-size: 10485760 # 10MB

# 日志配置
logging:
  level:
    com.happyvr: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/happyvr.log

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized